apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-logs
  namespace: postgres
spec:
  postgresVersion: 16
  users:
    - name: app
      databases:
        - app
  instances:
    - name: instance1
      metadata:
        annotations:
          monitoring-crunchy/psa-profile: restricted
      sidecars:
        replicaCertCopy:
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
      replicas: 1
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  backups:
    pgbackrest:
      jobs:
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
      repoHost:
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi
      sidecars:
        pgbackrest:
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 250m
              memory: 128Mi
        pgbackrestConfig:
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          log_min_messages: "info"
          log_connections: "on"
          log_disconnections: "on"
          log_statement: "all"
  instrumentation:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 250m
        memory: 128Mi
    config:
      exporters:
        otlp:
          endpoint: "alloy.loki.svc.cluster.local:4317"
          tls:
            insecure: true
    logs:
      exporters:
        - otlp
      batches:
        minRecords: 1
        maxRecords: 32
        maxDelay: 5s
